name: Configuration Flake Check

run-name: "flake check for ${{ github.repository }} : ${{ github.ref }}"

on: workflow_dispatch
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - run: nix flake check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
